name: osrm-backend

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: osrm-backend, ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}-${{ matrix.version }}
    strategy:
      fail-fast: true
      matrix:
        platform: [macos]
        version: [latest]
    env:
      GITHUB_TOKEN: ${{ github.token }}
      ARTIFACT_WORKFLOW: osrm-backend.yml

    steps:
    - name: Checkout osrm-backend
      uses: actions/checkout@v3
      with:
        repository: Project-OSRM/osrm-backend
        ref: db7946d76246cb10a5710c8f2851997417940b55
        submodules: true
        fetch-depth: 1
        path: osrm-backend

    - name: Build osrm-backend (macos)
      if: matrix.platform == 'macos'
      working-directory: osrm-backend
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1
        brew install lua tbb boost@1.76
        brew link boost@1.76
        
        mkdir build && cd build
        cmake ..
        make -j$((`sysctl -n hw.ncpu`+1))
        cd ../
        tar -czf osrm-backend.tgz build/libosrm* build/osrm-* include profiles third_party/flatbuffers third_party/variant
        du -h osrm-backend.tgz

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: osrm-backend_${{ matrix.platform }}
        path: osrm-backend/osrm-backend.tgz
        if-no-files-found: error
