name: Pull Request

on: [push, pull_request]

jobs:
  build_wheels:
    name: PR - cp*, ubuntu-22.04
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Project
      uses: actions/checkout@master

    - name: Run CIBuildWheel
      uses: pypa/cibuildwheel@v2.14.1
