name: Pull Request

on: [pull_request]

jobs:
  build_wheels:
    name: PR - cp*, linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@master

    - name: Run CIBuildWheel
      uses: pypa/cibuildwheel@v2.14.1
